version: '3.8'

services:
  mongo:
    image: mongo:8.0.5
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

volumes:
  data:
